services:
  express:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
      # Port for debugger
      - "9229:9229"
    environment:
      # Required for tsx hot module reloading - https://github.com/privatenumber/tsx/issues/266
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/app/server
    depends_on:
      - redis
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  webapp:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: development
    ports:
      - "5173:5173"
    environment:
      # Required for tsx hot module reloading - https://github.com/privatenumber/tsx/issues/266
      - CHOKIDAR_USEPOLLING=true
      - DOCKER_HOST=true
    volumes:
      - ./src:/app/src
    depends_on:
      - express
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
