apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx
  ports:
    - name: "http-port"
      port: 80
      targetPort: 80
    - name: "https-port"
      port: 443
      targetPort: 443
