apiVersion: apps/v1
kind: Deployment
metadata:
  name: lobby-server-deployment
spec:
  replicas: 2
  maxUnavailable: 1
  selector:
    matchLabels:
      name: lobby-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: lobby-server
    spec:
      restartPolicy: Always
      volumes:
        - name: nginx-secret
          secret:
            secretName: nginx-tls
      containers:
        - image: jonflinchum/pokemon-gambit-lobby-server:latest
          imagePullPolicy: Always
          name: lobby-server
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              memory: "1024Mi"
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /app/nginx
              name: nginx-secret
